### ISSUE TITLE
License and attribution

### ISSUE THREAD

**Issue by andwilr** [480-Design/Solar-Icon-Set#1]
Hey there,

Love the icons! I found them here: https://icones.js.org/collection/solar

According to that, they are licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) - is that accurate?

If so, it states attribution is required. If I use these icons as part of an entity's branding (website, business cards, other printed materials), where is the attribution required?

Thanks!

**Comment by MisterHims** [comment]
Hi @andwilr!

Solar Icon Set is indeed licensed under the Creative Commons Attribution 4.0 (CC BY 4.0) license, which allows for commercial use **but requires attribution**.

Regarding where to provide attribution, the key is that it should be accessible and reasonably prominent. Here are some suggestions:

- **Website**: Include the attribution in your "About" page, or in your terms and conditions under a section like "Credits" or "Third-Party Licenses."

- **Printed Materials**: You can add a small note on the material, such as at the bottom of a page or near the icons, stating something like: "Icons by Solar Icon Set". If space is limited, consider placing the credit in small next to the printer’s credit or other similar acknowledgments.

- **Branding Materials**: If the attribution cannot be included directly on the branding (e.g., logos), consider adding it to a brand guidelines document or similar resource that is shared with relevant stakeholders.

I also asked myself this question so I hope this helped you!

**Comment by andwilr** [comment]
Thanks @MisterHims!
